name: flower_shop
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Networking
  dio: ^5.4.0
  retrofit: ^4.9.2
  pretty_dio_logger: ^1.4.0

  # DI
  get_it: ^9.0.0
  injectable: ^2.7.0

  # Routing
  go_router: ^17.0.0

  # Localization
  easy_localization: ^3.0.8
  intl: ^0.20.2

  # Storage
  shared_preferences: ^2.5.3

  # UI
  flutter_svg: ^2.2.0
  shimmer: ^3.0.0
  skeletonizer: ^2.1.2
  flutter_otp_text_field: ^1.3.4

  # JSON
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code generation
  build_runner: ^2.4.8
  injectable_generator: ^2.10.0
  retrofit_generator: ^10.2.1
  json_serializable: ^6.8.0

  # Testing
  bloc_test: ^10.0.0
  mockito: ^5.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

easy_localization:
  path: assets/translations
  fallback_locale: en
  supported_locales: [en, ar]
