name: flower_shop
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  bloc: ^9.2.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.1
  easy_localization: ^3.0.8
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_otp_text_field: ^1.5.1+1
  flutter_svg: ^2.2.3
  get_it: ^9.2.0
  go_router: ^17.0.1
  injectable: ^2.7.1+4
  intl: ^0.20.2
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.5+1
  retrofit: ^4.9.2
  shared_preferences: ^2.5.4
  shimmer: ^3.0.0
  skeletonizer: ^2.1.2
  image_picker: ^1.2.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.10.5
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.9.1
  json_serializable: 6.11.2
  mockito: ^5.6.3
  retrofit_generator: ^10.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

easy_localization:
  path: assets/translations
  fallback_locale: en
  supported_locales: [en, ar]
